#cloud-config

# Exoscale template, change as needed per your instance config.  I would recommend making
# sure the mac of your private network is correct
# Group and user configuration
groups:
  - ubuntu [root,sys]
  - cloud-users
  
users:
  - default
  - name: xmrnode
    gecos: PawCloud XMR Node User
    home: /home/xmrnode
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    primary_group: xmrnode
    groups: cloud-users
    plain_text_passwd: 'pawcloud-xmrnode1'
    ssh_import_id: None
    lock_passwd: false

# Filesystem configuration
growpart:
    mode: auto
    devices: ["/"]
    ignore_growroot_disabled: false

# Files to write.
write_files:
  - path: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
    content: |
      network: {config: disabled}
  - path: /etc/netplan/20-eth0_custom.yaml
    content: |
      network:
        version: 2
        ethernets:
          eth0:
            match:
              name: eth0
            set-name: eth0
            dhcp4: true
            nameservers:
              search: [ns1.local, ns2.local]
              addresses: [8.8.8.8, 8.8.4.4]
  - path: /etc/netplan/21-eth1_custom.yaml
    content: |
      network:
        version: 2
        ethernets:
          eth1:
            match:
              name: eth1
            set-name: eth1
            dhcp4: false
            addresses: [10.0.0.2/24]
  - path: /home/xmrnode/00-install_xmrnode.sh
    content: |
      #!/bin/bash
      {
      . ~/.bashrc
      curl -L https://raw.githubusercontent.com/loopyd/pawcloud-xmr/main/xmrig-install.sh | bash
      } > /home/nodeproxy/install-log.txt
      full_path=$(realpath $0)
      rm -f "$full_path"

# Package manager
apt_update: true
apt_upgrade: true
apt_reboot_if_required: yes

# Commands to run
runcmd:
  - [ netplan, apply ]
  - [ sh, -xc, "cp /etc/skel/.* /home/xmrnode" ]
  - [ sh, -xc, "chown -R xmrnode:xmrnode /home/xmrnode" ]
  - [ sh, -xc, "chmod +x /home/xmrnode/00-install_xmrnode.sh" ]
  - [ su, -c, /home/xmrnode/00-install_xmrnode.sh, -s, /bin/bash, xmrnode ]
